/*************************************************************/
/* Automatically generated by './mkconfig.sh': do note edit! */
/*************************************************************/
#define LGL_OS "Linux sleek 4.10.0-33-generic x86_64"
#define LGL_COMPILED "Wed Sep 13 00:14:04 CEST 2017"
#define LGL_RELEASED "Thu Jul  7 10:21:35 CEST 2016"
#define LGL_VERSION "bbc"
#define LGL_ID "923038088b727dcc8bd03aa8dfb5013bd03bf8c4"
